version: '3.3'
services:

  pump-eth:
    container_name: pump-eth
    image: local-build/pump-ethereum
    restart: unless-stopped
#    ports:
#      - "8080:8080"
    environment:
      CASSANDRA_HOSTS: elassandra-search
      KAFKA_BROKERS: kafka:9092
      KAFKA_TRANSACTION_BATCH: 1000
      CHAIN: ETHEREUM
      CHAIN_NODE_URL: http://parity_eth:8545

  dump-eth:
    container_name: dump-eth
    image: local-build/dump-ethereum
    restart: unless-stopped
#    ports:
#      - "8080:8080"
    environment:
      CASSANDRA_HOSTS: elassandra-search
      KAFKA_BROKERS: kafka:9092
      CHAIN: ETHEREUM

  address-summary-eth:
    container_name: address-summary-eth
    image: local-build/address-summary-eth
    restart: unless-stopped
#    ports:
#      - "8080:8080"
    environment:
      CASSANDRA_HOSTS: elassandra-search
      KAFKA_BROKERS: kafka:9092
      CHAIN: ETHEREUM

networks:
    default:
        external:
            name: staging_default