version: '3.3'
services:

  search-api-1:
    container_name: search-api-1
    image: local-build/search-api
    restart: unless-stopped
    environment:
      CASSANDRA_HOSTS: elassandra-search
    ports:
      - "32901:8080"

  search-api-2:
    container_name: search-api-2
    image: local-build/search-api
    restart: unless-stopped
    environment:
      CASSANDRA_HOSTS: elassandra-search
    ports:
      - "32902:8080"

networks:
    default:
        external:
            name: staging_default