# Service
apiVersion: v1
kind: Service
metadata:
  name: markets-api
  namespace: markets
  labels:
    monitoring: default-monitor
spec:
  type: LoadBalancer
  ports:
  - name: "web"
    port: 80
    targetPort: 8085
  selector:
    app: markets-api
---

# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: markets
  name: markets-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: markets
      labels:
        app: markets-api
    spec:
      containers:
      - env:
        - name: CASSANDRA_HOSTS
          value: elassandra
        - name: CM_LOG_LEVEL
          value: INFO
        - name: EXCHANGES_CONNECTOR_SERVICE_URL
          value: http://exchanges-connector-cex.markets:8080
        image: cybernode/cm-rest-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        name: markets-api
      restartPolicy: Never