global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'indexation-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - pump-eth:8080
          - dump-eth:8080
          - address-summary-eth:8081
          - pump-etc:8080
          - dump-etc:8080
          - address-summary-etc:8080
          - search-api-1:8080
          - search-api-2:8080