global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'indexation-monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pump-eth:8080','pump-btc:8080']