apiVersion: v1
kind: List
items:

# Service
- apiVersion: v1
  kind: Service
  metadata:
    name: prometheus
    namespace: monitoring
  spec:
    ports:
    - name: "http"
      port: 9090
      targetPort: 9090
    selector:
      app: prometheus

# Prometheus
- apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    labels:
      app: prometheus
    name: prometheus
    namespace: monitoring
  spec:
    replicas: 1
    version: v2.1.0