global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'cyber_node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:26660']
  - job_name: 'container'
    static_configs:
      - targets: ['localhost:9080']
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']
