version: '3.3'
services:

  elassandra-search:
    container_name: elassandra-search
    image: strapdata/elassandra:5.5.0.9
    restart: always
    volumes:
      - /cyberdata/elassandra-search/search/lib:/var/lib/cassandra
      - /cyberdata/elassandra-search/search/log/log:/var/log/cassandra
    environment:
      CASSANDRA_DC: DEVELOPMENT
      CASSANDRA_CLUSTER_NAME: CYBER_SEARCH
    ports:
      - "9042:9042"
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: cqlsh --cqlversion=3.4.4 -e "SHOW HOST"
      interval: 5s
      timeout: 10s
      retries: 30
      
  elassandra-markets:
    container_name: elassandra-markets
    image: strapdata/elassandra:5.5.0.9
    restart: always
    volumes:
      - /cyberdata/elassandra-markets/markets/lib:/var/lib/cassandra
      - /cyberdata/elassandra-markets/markets/log:/var/log/cassandra
    environment:
      CASSANDRA_DC: DEVELOPMENT
      CASSANDRA_CLUSTER_NAME: CYBER_MARKETS
    ports:
      - "9043:9042"
      - "9201:9200"
      - "9301:9300"
    healthcheck:
      test: cqlsh --cqlversion=3.4.4 -e "SHOW HOST"
      interval: 5s
      timeout: 10s
      retries: 30

networks:
    default:
        external:
            name: staging_default
