apiVersion: v1
items:

# Service
- apiVersion: v1
  kind: Service
  metadata:
    name: parity-eth
  spec:
    ports:
    - name: "8545"
      port: 8545
      targetPort: 8545
    selector:
      chain: parity-eth
  status:
    loadBalancer: {}

# Deployment
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      chain: parity-eth
    name: parity-eth
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          chain: parity-eth
      spec:
        nodeSelector:
          chain-node: eth
        containers:
        - args:
          - --db-path
          - /cyberdata
          - --jsonrpc-hosts
          - all
          - --jsonrpc-interface
          - all
          - --jsonrpc-threads
          - "16"
          image: parity/parity:stable-release
          name: parity-eth
          ports:
          - containerPort: 8545
          resources: {}
          volumeMounts:
          - mountPath: /cyberdata
            name: parity-eth-claim0
        restartPolicy: Always
        volumes:
        - name: parity-eth-claim0
          persistentVolumeClaim:
            claimName: parity-eth-claim0
  status: {}

# Volume Claim
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: parity-eth-claim0
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 200Gi
    storageClassName: fast
  status: {}

kind: List
metadata: {}